### ISSUE TITLE
User story: Love runing

### ISSUE THREAD

**Issue by FabrizioAdi** [FabrizioAdi/My-first-agile-project#3]
As a **user** I can **provide my opinion** so that **I can select an answer from the poll**.

**Comment by FabrizioAdi** [comment]
# Acceptance Criteria:
*  the option should be provided as a checkbox
* the option should appear next to the submit button

**Comment by FabrizioAdi** [comment]
## Tasks:
- [] Task1 Poll design in HTML and CSS to including checbox, and name of submiter
- [] Task2 Create a new field to write down the opinion
- [] Task3 Update the controller function
- [] Task4 Update unit test scripts
- [] Task5Test the functionality
